export interface ProDefinition {
    id: number;
    name: string;
}

export const prosDefinition: ProDefinition[] = [
    { id: 1, name: "Aloe" },
    { id: 2, name: "Badaboom" },
    { id: 3, name: "Beakit" },
    { id: 4, name: "Blitzbois" },
    { id: 5, name: "Broc" },
    { id: 6, name: "Buckshot" },
    { id: 7, name: "Burnout" },
    { id: 8, name: "Cacticrue" },
    { id: 9, name: "Cactiking" },
    { id: 10, name: "Chonk" },
    { id: 11, name: "Chronodrop" },
    { id: 12, name: "D.F.A." },
    { id: 13, name: "Deadeye" },
    { id: 14, name: "DJ-Pushit" },
    { id: 15, name: "Fendor" },
    { id: 16, name: "Flingshot" },
    { id: 17, name: "Floraphant" },
    { id: 18, name: "Furble" },
    { id: 19, name: "Gorrit" },
    { id: 20, name: "Grumph" },
    { id: 21, name: "Heartburn" },
    { id: 22, name: "Hornelius" },
    { id: 23, name: "Infernus" },
    { id: 24, name: "Janz" },
    { id: 25, name: "Lavadrop" },
    { id: 26, name: "Lumph" },
    { id: 27, name: "Magmalisk" },
    { id: 28, name: "Pocus" },
    { id: 29, name: "Punks" },
    { id: 30, name: "Push drop" },
    { id: 31, name: "Pyrokeet" },
    { id: 32, name: "Razerpaw" },
    { id: 33, name: "RB-IT" },
    { id: 34, name: "Rekkit" },
    { id: 35, name: "Sembler" },
    { id: 36, name: "Shellshock" },
    { id: 37, name: "Shooticrue" },
    { id: 38, name: "Shortfuse" },
    { id: 39, name: "Skye" },
    { id: 40, name: "Slowclaw" },
    { id: 41, name: "Spord" },
    { id: 42, name: "Tailblazer" },
    { id: 43, name: "TD-PL" },
    { id: 44, name: "Vitadrop" },
    { id: 45, name: "Volcrab" },
    { id: 46, name: "Wotchy" },
    { id: 47, name: "Zipzap" },
];
